apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
  annotations:
    policies.kyverno.io/title: Require Non-Root Containers
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - payments
      validate:
        message: "Pods must set spec.securityContext.runAsNonRoot=true."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
    - name: block-container-root-user
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - payments
      validate:
        message: "Containers must not run as UID 0."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.runAsUser || '-1' }}"
                    operator: Equals
                    value: 0
