apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - deployment-ledger-api.yaml
  - deployment-reporting.yaml
  - services.yaml
  - ingress.yaml
  - networkpolicies.yaml
  - rbac-personas.yaml
